/**
 * Willow Bend — the Master Planned Community built on a buried wetland.
 * Arterial loop, a swale easement, eight occupied lots, and the retention
 * pond with the old spring (`>`) at its heart. The water remembers.
 *
 * Legend: see maps/world.ts. 24×18.
 */
export const WILLOW_BEND = `
........................
..t...t.....t...t..t....
..r...H.....r...c..t....
........................
.AAAAAAAAAAAAAAAAAAAA...
.A..................A...
.A.r..t.H.....r..t..A...
.A..................A...
.A....SSS...........A...
.A.t..S......t......A...
.AAAAAS.............A...
......S....PPP......A...
..c...S...PPPPP.p...A...
......S...PP>PP..AAAA...
..t....B..PPPPP.....t...
....t......PPP..t.......
..t.....................
........................
`;
